"""Remove same_subject_only from constraints

Revision ID: 37b548a295aa
Revises: d1fc34156f09
Create Date: 2025-11-20 12:07:49.256525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37b548a295aa'
down_revision = 'd1fc34156f09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lesson_type_constraint', schema=None) as batch_op:
        batch_op.drop_column('same_subject_only')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lesson_type_constraint', schema=None) as batch_op:
        batch_op.add_column(sa.Column('same_subject_only', sa.BOOLEAN(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
