"""Add is_special to Room

Revision ID: d1fc34156f09
Revises: 31e3bae8a48e
Create Date: 2025-11-20 09:25:57.314320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1fc34156f09'
down_revision = '31e3bae8a48e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_special', sa.Boolean(), nullable=False, server_default='false')) # <-- ИЗМЕНЕНИЕ ЗДЕСЬ
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.drop_column('is_special')

    # ### end Alembic commands ###
